export const constantsList = {
	// Common
	LOADING_TEXT: "Please wait...",
	GST_TAX: 118,
	USER_MENU_KEY_LENGTH: 15,
	SUPER_ADMIN_ROLE_ID: 1,
	DATATABLE_PER_PAGE: "10,25,50,100",
	SESSION_CHECK_DURATION: 30, // In seconds
	NOTIFICATION_CHECK_DURATION: 30, // In seconds

	// Announcements
	ANNOUNCEMENT_HEADING_TEXT_LIMIT: 150,
	ANNOUNCEMENT_IMG_MAX_SIZE: 2048,

	// Dashboard
	PLAN_RENEWING_DAYS: 5,

	// Facing Issue
	FACING_ISSUE_DOC_MAX_SIZE: 2048,

	// Others
	OTT_LIST_LIMIT: 4,

	// No of items per load
	BULK_LIST_LIMIT: 5,
	CATEGORY_LIMIT: 60,
	ISP_LIST_LIMIT: 20,
	ISP_WALLET_PLANS_LIST_LIMIT: 60,
	MY_WALLET_LIST_LIMIT: 10,
	OPERATOR_LIMIT: 20,
	OPERATOR_WALLET_LIST_LIMIT: 60,
	PLANS_LIMIT: 12,
	PROMOTION_LIMIT: 10,
	FACING_ISSUE_LIMIT: 10,
	RESET_PASSWORD_LIMIT: 20,
	ROLE_LIMIT: 60,
	SUBSCRIBER_LIMIT: 20,
	TEAM_LIMIT: 20,
	TERMS_DOCUMENT_LIMIT: 60,

	// input fields limit
	INPUT_MAXLENGTH: 50,
	TEXT_AREA_MAXLENGTH: 250,
	MAXLENGTH_NAME: 25,
	MAXLENGTH_LOGIN_ID: 25,
	MAXLENGTH_DISPALY_NAME: 50,
	MAXLENGTH_EMAIL: 50,
	MAXLENGTH_DISCOUNT: 3,
	MAXLENGTH_COUPON: 5,

	// parner id limit
	PARTNER_ID_MIN_LENGTH: 4,
	PARTNER_ID_MAX_LENGTH: 30,

	// Amounts/Balance
	MIN_ADD_BALANCE: 5000,
	MIN_ADD_BALANCE_OPERATOR_WALLET: 1,

	// Promotion
	CUSTOM_TEXT_LIMIT: 150,
	PROMOTION_IMG_MAX_SIZE: 2048,

	// Coupon
	GST_PERCENT: 18,
	COUPON_EXPIRY_IN_DAYS: 180,
};
