const prefix = "des_";

export const TABLE_LIST = {
	TENDER_LIST_USER_ACTION: prefix + "tender_list_user_action",
	FINANCIER_LIST: prefix + "financier_list",
	SOURCE_TAG: prefix + "source_tag_master",
	REQUIRED_DOCUMENT: prefix + "required_documents",
	ADD_LINK: prefix + "add_link",
	SITE_VISIT: prefix + "site_visit",
	ADD_TENDER: prefix + "tender_list",
	SITE_VISIT_USER: prefix + "site_visit_user",
	SITE_VISIT_ACTION_USER: prefix + "site_visit_action_user",
	ANNOUNCEMENTS: prefix + "announcements",
	API_REQUEST_QUEUE: prefix + "api_request_queue",
	APV_CHECK_LOG: prefix + "apv_check_log ",
	AUDIT_LOGS: prefix + "audit_logs",
	AUTO_RENEW_SUBSCRIBERS: prefix + "auto_renew_subscribers",
	AUTO_RENEW_TRANSACTIONS: prefix + "auto_renew_transactions",
	AUTO_RENEWAL_STATUS_CHANGE_REQUESTS: prefix + "auto_renewal_status_change_requests",
	BANK_MASTER: prefix + "bank_master",
	BOUQUET_MASTER: prefix + "bouquet_master",
	BOUQUET_OTT_MAPPING: prefix + "bouquet_ott_mapping",
	BULK_FILES_LIST: prefix + "bulk_files_list",
	BULK_RENEW_INTENT: prefix + "bulk_renew_intent",
	BULK_SUB_CREATION_ACTIVATION: prefix + "bulk_subscriber_creation_activation",
	BULK_SUB_CREATION: prefix + "bulk_subscriber_creation",
	BULK_SUB_PLAN_ACTIVATION: prefix + "bulk_subscriber_plan_activation",
	BULK_SUB_PLAN_ADVANCE_RENEWAL: prefix + "bulk_subscriber_plan_advance_renewal",
	BULK_SUB_PLAN_CANCELLATION: prefix + "bulk_subscriber_plan_cancellation",
	BULK_SUB_PLAN_FUTURE_ACTIVATION: prefix + "bulk_subscriber_plan_future_activation",
	BULK_SUB_PLAN_SWITCH: prefix + "bulk_subscriber_plan_switch",
	BULK_UPGRADE_EXISTING_PLAN: prefix + "bulk_upgrade_existing_plan",
	CALC_ACTIVATIONS: prefix + "calc_activations",
	CALC_SUBSCRIBERS: prefix + "calc_subscribers",
	CALC_UPCOMING_RENEWALS: prefix + "calc_upcoming_renewals",
	CITY_MASTER: prefix + "city_master",
	CLAIM_API_LOGS: prefix + "claim_api_logs",
	CLAIM_API_PLAN_MAPPING: prefix + "claim_api_plan_mapping",
	CONFIG: prefix + "config",
	COUNTRY_MASTER: prefix + "country_master",
	COUPON_LIST: prefix + "coupon_list",
	COUPON_REQUESTS: prefix + "coupon_requests",
	COUPON_USAGE: prefix + "coupon_usage",
	CRON_JOBS: prefix + "cron_jobs",
	DISABLE_GLOBAL_ACTIVATION_MODE_API: prefix + "disable_global_activation_mode_api",
	DISTRIBUTOR_BOUQUET_MAPPING: prefix + "distributor_bouquet_mapping",
	DISTRIBUTOR_COMMISSION: prefix + "distributor_commission",
	DISTRICT_MASTER: prefix + "district_master",
	EMAIL_LOGS: prefix + "email_logs",
	EMAIL_SEND_LIST: prefix + "email_send_list",
	ENTITY_BALANCE_TRANSACTIONS: prefix + "entity_balance_transactions",
	ENTITY_BALANCE: prefix + "entity_balance",
	ENTITY_BOUQUET_MAPPING: prefix + "entity_bouquet_mapping",
	ENTITY_CATEGORY_DATA: prefix + "entity_category_data",
	ENTITY_CATEGORY: prefix + "entity_category",
	ENTITY_PAYMENT: prefix + "entity_payment",
	ENTITY_TRANSFER_BALANCE_TRANSACTIONS: prefix + "entity_transfer_balance_transactions",
	ENTITY_TYPES: prefix + "entity_types",
	HELP_CONTENT: prefix + "help_content",
	ISP_AUTO_RENEW_LOGS: prefix + "isp_auto_renew_logs",
	ISP_CONSENT_LOG: prefix + "isp_consent_logs",
	ISP_FREEZE_UNFREEZE_LOGS: prefix + "isp_freeze_unfreeze_logs",
	ISP_OPERATOR_BOUQUET_MAPPING: prefix + "isp_operator_bouquet_mapping",
	ISP_SYNC_PLAN: prefix + "isp_sync_plan",
	ISP_WALLET_EXPIRY_DATE: prefix + "isp_wallet_expiry_date",
	LOGIN_AS_USER: prefix + "login_as_user",
	MENU_MASTER: prefix + "menu_master",
	NODE_API_LOGS: prefix + "node_api_logs",
	NOTIFICATIONS: prefix + "notifications",
	OPERATOR_SUBSCRIBER_BOUQUET_MAPPING: prefix + "operator_subscriber_bouquet_mapping",
	OTP_GENERATION: prefix + "otp_generation",
	OTP_VERIFY_ATTEMPTS: prefix + "otp_verify_attempts",
	OTT_MASTER: prefix + "ott_master",
	PAYMENT_GATEWAY_LOGS: prefix + "payment_gateway_logs",
	PROMOTIONS: prefix + "promotions",
	ROLE_MASTER: "role_master",
	SMS_LOG: prefix + "sms_logs",
	STAKEHOLDER_DETAILS: prefix + "stakeholder_details",
	STAKEHOLDERS: prefix + "stakeholders",
	STATE_MASTER: prefix + "state_master",

	SUBSCRIBER_AUTO_RENEWAL_PLAN_CHANGE_LOGS: prefix + "subscriber_auto_renewal_plan_change_logs",
	SUBSCRIBER_MASTER: prefix + "subscriber_master",
	SUBSCRIBER_PLAN_ACTIVATIONS_CHECK_LOGS: prefix + "subscriber_plan_activations_check_logs",
	SUBSCRIBER_PLAN_DETAILS: prefix + "subscriber_plan_details",
	SUBSCRIBER_PLAN_HISTORY: prefix + "subscriber_plan_history",
	SUBSCRIBER_PLAN_LIST: prefix + "subscriber_plan_list",
	SUBSCRIBER_PLAN_SYNC_CHECK_LOGS: prefix + "subscriber_plan_sync_check_logs",
	SUBSCRIBER_RENEW_INTENTS: prefix + "subscriber_renew_intents",
	SUBSCRIBERS_AUTO_RENEW_LOGS: prefix + "subscribers_auto_renew_logs",
	TERMS_DOCUMENTS: prefix + "terms_documents",
	TRANSACTIONS: prefix + "transactions",
	TRANSFER_LIMIT_LOGS: prefix + "transfer_limit_logs",
	USER_MASTER: "user_master",
	USER_PASSWORD_LOGS: "user_password_logs",
	WEBHOOK_QUEUE: prefix + "webhook_queue",
	ZONE_MASTER: prefix + "zone_master",
	PROJECT_LIST: prefix + "project",
	LEAD_GENERATION: prefix + "lead_generation",
	SENDER: prefix + "senders",
	CAMPAIGNS: prefix + "campaigns",
	CAMPAIGNSRECIPIENTS: prefix + "campaign_recipients",

	// Add new tables above this line
	ONBOARDING: "onboardings",
	FIELDENGINEER: "field_engineers",
	ONBOARDING_ADDRESS: "engineer_addresses",
	ENGINEER_DOCUMENTS: "engineer_documents",
	ENGINEER_QUALIFICATIONS: "engineer_qualifications",
	ENGINEER_USER_CREATION: "engineer_user_creation",
	ENGINEER_BANK_DETAILS: "engineer_bank_details",
	ENGINEER_BENEFITS: "engineer_benefits",
	ENGINEER_RATINGS: "engineer_ratings",
};
