export const financierData = [
"Abu Dhabi Fund for Development (ADFD)",
"African Development Bank (AfDB)",
"African Export-Import Bank (AFREXIM)",
"Agence Francaise De Development (AFD)",
"Agency for International Business and Cooperation (EVD)",
"Agency for Technical Cooperation and Development (ACTED)",
"Agency for the Cooperation of Energy Regulators (ACER)",
"Agency of Montenegro for Economic Restructuring and Foreign Investment",
"Arab Fund for Economic and Social Development",
"Asia-Pacific Economic Cooperation (APEC)",
"Asian Development Bank (ADB)",
"Asian Infrastructure Investment Bank (AIIB)",
"Australian Agency for International Development (AusAID)",
"Austrian Development Agency (ADA)",
"Belgian Development Corporation (BDC)",
"Belgian Technical Cooperation (BTC)",
"Body of European Regulators of Electronic Communications (BEREC)",
"Brazilian Development Bank (BNDES)",
"Canadian International Development Agency (CIDA)",
"Caribbean Development Bank (CDB)",
"Central Finance and Contracts Unit (CFCU)",
"Community Plant Variety Office (CPVO)",
"Comprehensive Nuclear-Test-Ban Treaty Organization (CTBTO)",
"COOPI Cooperazione Internazionale",
"Council for Development & Reconstruction",
"Danish International Development Agency (DANIDA)",
"Department For International Development",
"Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH",
"Deutsche Gesellschaft für Technische Zusammenarbeit (GTZ)",
"East African Development Bank (EADB)",
"Economic Commission for Europe (ECE)",
"Economic Commission for Latin America and the Caribbean",
"Economic Commission for Western Asia (ECWA)",
"Education, Audiovisual and Culture Executive Agency (EACEA)",
"Eurasian Development Bank (EDB)",
"Euratom Supply Agency (ESA)",
"EuropeaAid",
"European Agency for Safety and Health at Work (EU-OSHA)",
"European Asylum Support Office (EASO)",
"European Aviation Safety Agency (EASA)",
"European Bank for Reconstruction and Development (EBRD)",
"European Banking Authority (EBA)",
"European Border and Coast Guard Agency (Frontex)",
"European Centre for Disease Prevention and Control (ECDC)",
"European Chemicals Agency (ECHA)",
"European Commission",
"European Data Protection Supervisor (EDPS)",
"European Defence Agency (EDA)",
"European Environment Agency (EEA)",
"European Food Safety Authority (EFSA)",
"European GNSS Agency (GSA)",
"European Institute for Gender Equality (EIGE)",
"European Investment Bank (EIB)",
"European Labour Authority (ELA)",
"European Maritime Safety Agency (EMSA)",
"European Medicines Agency (EMA)",
"European Monitoring Centre for Drugs and Drug Addiction (EMCDDA)",
"European Network and Information Security Agency (ENISA)",
"European Public Prosecutors Office (EPPO)",
"European Railway Agency (ERA)",
"European Securities and Markets Authority (ESMA)",
"European Training Foundation (ETF)",
"European Union Agency for Law Enforcement Cooperation (Europol)",
"European Union Intellectual Property Office (EUIPO)",
"European University Institute (EUI)",
"Executive Agency for Small and Medium-sized Enterprises (EASME)",
"Finnish Fund for Industrial Cooperation Ltd (FINNFUND)",
"Food And Agriculture Organisation (FAO)",
"Ford Foundation",
"Fundamental Rights Agency (FRA)",
"Global Environment Facility (GEF)",
"Global Fund to Fight AIDS, Tuberculosis and Malaria (GFFATM)",
"International Atomic Energy Agency (IAEA)",
"International Civil Aviation Organization (ICAO)",
"International Criminal Court (ICC)",
"International Finance Corporation (IFC)",
"International Labour Organization",
"International Maritime Organization (IMO)",
"International Monetary Fund (IMF)",
"International Organization for Migration (IOM)",
"International Telecommunication Union (ITU)",
"International Trade Centre (ITC)",
"Islamic Development Bank (ISDB)",
"Japan Bank for International Cooperation (JBIC)",
"Japan International Cooperation Agency (JICA)",
"KFW Bankengruppe (German Development Bank)",
"Kuwait Fund for Arab Economic Development (KFAED)",
"Millennium Challenge Account (MCA)",
"Multilateral Investment Guarantee Agency (MIGA)",
"New Development Bank (NDB)",
"Nordic Investment Bank (NIB)",
"Office of the United Nations High Commissioner for Human Rights (OHCHR)",
"OPEC Fund for International Development (OFID)",
"Organisation for Economic Co-operation and Development (OECD)",
"Pan American Health Organization",
"Research Executive Agency (REA)",
"Saudi Fund For Development (SFD)",
"Save The Children",
"United Nations Development Programme (UNDP)",
"United Nations Environment Programme (UNEP)",
"United Nations High Commissioner for Refugees (UNHCR)",
"United Nations Industrial Development Organization (UNIDO)",
"United Nations International Children's Emergency Fund (UNICEF)",
"United Nations Office for Project Services (UNOPS)",
"United Nations Population Fund (UNFPA)",
"United States Agency for International Development (USAID)",
"Universal Postal Union (UPU)",
"World Bank (WB)",
"World Food Programme (WFP)",
"World Health Organization (WHO)",
"World Intellectual Property Organization (WIPO)",
"World Trade Organization (WTO)"
];