const apiList = {
	announcements: {
		getAnnouncementCount: "announcements/getAnnouncementCount",
		list: "announcements/list",
		add: "announcements/add",
		get: "announcements/get/",
		update: "announcements/update",
		deactivate: "announcements/deactivate",
	},
	internal: {
		getSubscriberDetails: "api/internal/getSubscriberDetails",
	},
	api: {
		cancelSubscriberPlan: "api/cancelSubscriberPlan",
		createNewSubscriber: "api/createNewSubscriber",
		getHealthChecked: "api/getHealthChecked",
		getIspBalance: "api/getIspBalance",
		getOperatorBalance: "api/getOperatorBalance",
		getOperatorPlansList: "api/getOperatorPlansList",
		getSubscriberDetails: "api/getSubscriberDetails",
		superIspAccountAutomation: "api/superIspAccountAutomation",
		ispAccountAutomation: "api/ispAccountAutomation",
		operatorAccountAutomation: "api/operatorAccountAutomation",
		subscriberActivation: "api/subscriberActivation",
		subscriberPackActivity: "api/subscriberPackActivity",
	},
	apiV4_0: {
		cancelSubscriberPlan: "api/v4.0/cancelSubscriberPlan",
		checkQueueRequestStatus: "api/v4.0/checkQueueRequestStatus",
		createAutoRenewalIntent: "api/v4.0/createAutoRenewalIntent",
		createRenewalIntent: "api/v4.0/createRenewalIntent",
		getAutoRenewStatusChangeRequests: "api/v4.0/getAutoRenewStatusChangeRequests",
		getIspBalance: "api/v4.0/getIspBalance",
		getOperatorBalance: "api/v4.0/getOperatorBalance",
		getPlanList: "api/v4.0/getOperatorPlansList",
		getRenewalRequests: "api/v4.0/getRenewalRequests",
		getSubscriberDetails: "api/v4.0/getSubscriberDetails",
		processClaim: "api/v4.0/processClaim",
		subscriberActions: "api/v4.0/subscriberActions",
		updateAutoRenewStatusChange: "api/v4.0/updateAutoRenewStatusChange",
		updateCmsPlanStatus: "api/v4.0/updateCmsPlanStatus",
		updateCouponRedeemStatus: "api/v4.0/updateCouponRedeemStatus",
		updateRenewalRequest: "api/v4.0/updateRenewalRequest",
	},
	auth: {
		checkLogin: "auth/authenticate",
	},
	bulkActivity: {
		downloadUploadedFile: "bulkActivity/downloadFile",
		getBulkActivityCount: "bulkActivity/getCount",
		getUploadedFileList: "bulkActivity/getUploadedFileList",
		updateAccountStatus: "bulkActivity/updateAccountStatus",
		updateWalletExpiry: "bulkActivity/updateWalletExpiry",
		uploadFile: "bulkActivity/uploadFile",
	},
	category: {
		add: "category/add",
		edit: "category/edit",
		get: "category/get/",
		getActivities: "category/getActivities",
		getCount: "category/getCount",
		list: "category/list",
	},
	common: {
		getBankList: "common/getBankList",
		getCityList: "common/getCityList",
		getDistrictList: "common/getDistrictList",
		getIspCategories: "common/getIspCategories",
		getStateList: "common/getStateList",
	},
	controlCenter: {
		getARIspList: "controlCenter/getARIspList",
		getIspAccountStatusHistory: "controlCenter/getIspAccountStatusHistory/",
		getIspAccountStatusList: "controlCenter/getIspAccountStatusList",
		getIspARCount: "controlCenter/getIspARCount",
		getIspHistory: "controlCenter/getIspHistory/",
		getIspTransferLimitCount: "controlCenter/getTransferLimitIspCount",
		getIspTransferLimitHistory: "controlCenter/getIspTransferLimitHistory/",
		getIspWalletExpiry: "controlCenter/getIspWalletExpiry",
		getIspWalletExpiryHistory: "controlCenter/getIspWalletExpiryHistory/",
		getTransferLimitIspList: "controlCenter/getIspTransferLimitList",
		updateIspAccountStatus: "controlCenter/updateIspAccountStatus",
		updateIspARStatus: "controlCenter/updateIspARStatus",
		updateIspTransferLimitStatus: "controlCenter/updateIspTransferLimitStatus",
	},
	coupon: {
		assignCouponToRetailer: "coupon/assignCouponToRetailer",
		createCouponRequest: "coupon/createCouponRequest",
		getCouponList: "coupon/getCouponList",
		getCouponListCount: "coupon/getCouponListCount",
		getCouponListDetail: "coupon/getCouponListDetail/",
		getCouponRequest: "coupon/getCouponRequest/",
		getCouponRequestCount: "coupon/getCouponRequestCount",
		getCouponRequestList: "coupon/getCouponRequestList",
		getCouponsForAssign: "coupon/getCouponsForAssign",
		getDistAvailableCoupons: "coupon/getDistAvailableCoupons",
		getListCsv: "coupon/getListCsv",
		getPlanList: "coupon/getPlanList",
		getRetailerList: "coupon/getRetailerList",
		getWalletBalance: "coupon/getWalletBalance",
	},
	couponDistributor: {
		addRetailer: "distributors/addRetailer",
		addStackHolder: "distributors/addStackHolder",
		createCommission: "distributors/createCommission",
		creditDebitBalance: "distributors/creditDebitBalance",
		edit: "distributors/edit",
		get: "distributors/get/",
		getCount: "distributors/getCount",
		getCouponDistributor: "distributors/couponDistributor",
		getDistributorPlans: "distributors/getDistributorPlans",
		getIspList: "distributors/getIspList",
		getIspPlanList: "distributors/getIspPlanList",
		getIspPlansCount: "distributors/getIspPlanCount",
		list: "distributors/getList",
		priceUpdate: "distributors/priceUpdate",
		syncPlan: "distributors/syncPlan",
		teamList: "distributors/teamList",
	},
	tender: {
		add: "tender/add",
		list: "tender/list",
	},
	dashboard: {
		cancelAutoRenewalRequest: "dashboard/cancelAutoRenewalRequest",
		cancelIntent: "dashboard/cancelIntent",
		getActivationStatus: "dashboard/getActivationStatus",
		getAutoRenewalIntentCount: "dashboard/getAutoRenewalIntentCount",
		getAutoRenewalIntentList: "dashboard/getAutoRenewalIntentList",
		getCouponAllocation: "dashboard/getCouponAllocation",
		getCouponStatus: "dashboard/getCouponStatus",
		getDistributorRetailerPerformance: "dashboard/getDistributorRetailerPerformance",
		getDistributorRetailerPlans: "dashboard/getDistributorRetailerPlans",
		getDistributorRetailerPlansAllocation: "dashboard/getDistributorRetailerPlansAllocation",
		getIspOperAutoRenewalIntentList: "dashboard/getIspOperAutoRenewalIntentList",
		getIspOperRenewalIntentList: "dashboard/getIspOperRenewalIntentList",
		getIspWalletStatus: "dashboard/getIspWalletStatus",
		getIspWiseStatus: "dashboard/getIspWiseStatus",
		getLastTopUp: "dashboard/getLastTopUp",
		getMyPlans: "dashboard/getMyPlans",
		getMyPlansPerformance: "dashboard/getMyPlansPerformance",
		getMyWallet: "dashboard/getMyWallet",
		getMyWalletActivity: "dashboard/getMyWalletActivity",
		getOperatorWalletStatus: "dashboard/getOperatorWalletStatus",
		getOperatorWiseStatus: "dashboard/getOperatorWiseStatus",
		getPlanRenewals: "dashboard/getPlanRenewals",
		getPlanRenewalsList: "dashboard/getPlanRenewalsList",
		getRenewalIntentCount: "dashboard/getRenewalIntentCount",
		getRenewalIntentList: "dashboard/getRenewalIntentList",
		getRetailerList: "dashboard/getRetailerList",
		getSubscriberPlanStats: "dashboard/getSubscriberPlanStats",
		getSubscriberStatus: "dashboard/getSubscriberStatus",
		operatorBalanceList: "dashboard/operatorBalanceList",
		renewIntent: "dashboard/renewIntent",
	},
	dashboardNew: {
		getActivationRenewalsData: "dashboard/getActivationRenewalsData",
		getRenewIntentCount: "dashboard/getRenewIntentCount",
		getRenewIntentCountNew: "dashboard/getRenewIntentCountNew",
		getSubscriberCount: "dashboard/getSubscriberCount",
		getTopPlanPerformanceData: "dashboard/getTopPlanPerformanceData",
		getPlanPerformanceData: "dashboard/getPlanPerformanceData",
		refreshMyPerformanceCount: "dashboard/refreshMyPerformanceCount",
		refreshSubscribersCount: "dashboard/refreshSubscribersCount",
	},
	facingIssue: {
		add: "facingIssue/add",
		contactUpdate: "facingIssue/contactUpdate",
		statusUpdate: "facingIssue/statusUpdate",
		getContact: "facingIssue/getContact",
		list: "facingIssue/list",
		update: "facingIssue/update",
	},
	faq: {
		addUpdateFaq: "faq/addUpdateFaq",
		enableDisableFaq: "faq/enableDisableFaq",
		getFaq: "faq/getFaq/",
		getFaqList: "faq/getFaqList",
		getFaqListCount: "faq/getFaqListCount",
		getTopicList: "faq/getTopicList",
	},
	forgetPassword: {
		checkAndSendOtp: "auth/forgetPasswordCheckAndSendOtp",
		verifyOtp: "auth/forgetPasswordVerifyOtp",
		setNewPassword: "auth/forgetPasswordSetPassword",
	},
	help: {
		getHelpContent: "help/list",
	},
	loginAsUser: {
		generateToken: "profile/generateTokenForLoginAsUser",
		verifyToken: "auth/validateTokenForLoginAsUser",
	},
	isp: {
		addStackHolder: "isp/addStackHolder",
		creditDebitBalance: "isp/creditDebitBalance",
		downloadReport: "isp/downloadReport",
		edit: "isp/edit",
		editSuperIsp: "isp/editSuperIsp",
		get: "isp/get/",
		getCount: "isp/getCount",
		getIspPlanList: "isp/getIspPlanList",
		getIspPlansCount: "isp/getIspPlanCount",
		getIspPlansForSelection: "isp/getIspPlansForSelection",
		getOperatorList: "isp/getOperatorList",
		getWalletExpiryCount: "isp/getWalletExpiryCount",
		inactivatePlan: "isp/inactivatePlan",
		list: "isp/getList",
		replacePlan: "isp/replacePlan",
		syncPlan: "isp/syncPlan",
		teamList: "isp/teamList",
		unassignPlan: "isp/unassignPlan",
	},
	myWallet: {
		get: "myWallet/get",
	},
	notifications: {
		getCount: "notifications/getCount",
		getUnreadList: "notifications/getUnreadList",
		clear: "notifications/clear",
	},
	operators: {
		add: "operators/add",
		edit: "operators/edit",
		editUserStatus: "operators/editUserStatus",
		get: "operators/get/",
		getOperatorCount: "operators/getCount",
		getPlanList: "operators/getPlanList",
		list: "operators/list",
		teamAdd: "operators/teamAdd",
		teamEdit: "operators/teamEdit",
		teamList: "operators/teamList",
		unassignPlan: "operators/unassignPlan",
	},
	operatorWallet: {
		addOperatorBalance: "operatorWallet/addBalance",
		downloadReport: "operatorWallet/downloadReport",
		get: "operatorWallet/get/",
		getCount: "operatorWallet/getCount",
		getWalletHistory: "operatorWallet/getWalletHistory",
		list: "operatorWallet/list",
		revokeBalance: "operatorWallet/revoke",
	},
	partners: {
		getCouponDistributorList: "partners/getCouponDistributorList",
		getCouponDistributorListFilter: "partners/getCouponDistributorList/",
		getIspList: "partners/getIspList/",
		getOperatorByCatId: "partners/getOperatorByCatId",
		getOperatorListByIsp: "partners/getOperatorListByIsp",
		getSuperDistributorList: "partners/getSuperDistributorList",
		getSuperIspList: "partners/getSuperIspList",
		getTopLevelIspList: "partners/getTopLevelIspList",
	},
	payments: {
		checkStatus: "payments/checkStatus",
		ispCreateNewOrder: "payments/ispCreateNewOrder",
		postPaymentDataUpdate: "payments/postPaymentDataUpdate",
		saveLogs: "payments/saveLogs",
		updatePayment: "payments/updatePayment",
	},
	plans: {
		addDistPlanRate: "plans/addDistPlanRate",
		addIspPlanRate: "plans/addIspPlanRate",
		addPlanRate: "plans/addPlanRate",
		get: "plans/get",
		getForActivation: "plans/getForActivation",
		getPlanCount: "plans/getPlanCount",
		getPlansListForUpgrade: "plans/getPlansListForUpgrade",
		getRetailerPlansList: "plans/getRetailerPlansList",
	},
	profile: {
		checkAutoRenew: "profile/checkAutoRenewalStatus",
		checkBalance: "profile/checkBalance",
		checkPasswordExpiry: "profile/checkPasswordExpiry",
		checkSession: "profile/checkSession",
		checkUpcomingExpiry: "profile/checkUpcomingExpiry",
		downloadApiToken: "profile/downloadApiToken",
		getProfileData: "profile/get",
		getMenu: "profile/getMenu",
		regenerateToken: "profile/regenerateToken",
		sendTokenOnMail: "profile/sendTokenOnMail",
		setChangePassword: "profile/changePassword",
		setForcePassword: "profile/setForcePassword",
		updateProfile: "profile/update",
		getTickerBanner: "profile/getTickerBanner",
	},
	promotions: {
		add: "promotions/add",
		deactivate: "promotions/deactivate",
		get: "promotions/get/",
		getPromotionCount: "promotions/getPromotionCount",
		list: "promotions/list",
		update: "promotions/update",
	},
	regions: {
		get: "regions/get/",
		getCount: "regions/getCount",
		getIspList: "regions/getIspList",
		teamList: "regions/teamList",
		getOperatorList: "regions/getOperatorList",
		getSuperIspList: "regions/getSuperIspList",
		list: "regions/list",
	},
	report: {
		getActivationReport: "reports/activation",
		getCouponReport: "reports/getCouponRequest",
		getCouponUsageReport: "reports/getCouponUsage",
		getExpiredSubscriberReport: "reports/expiredSubscriber",
		getIspDayWiseWalletReport: "reports/getIspDayWiseWallet",
		getIspWalletReport: "reports/ispWallet",
		getOperatorLedgerReport: "reports/ledger",
		getPayoutReport: "reports/getPayoutReport",
		getPlanDetailsReport: "reports/getPlanDetails",
		getPlanOttReport: "reports/getPlanOtts",
		getSubscriberDetailsReport: "reports/subscriberDetails",
		getSubscriberHistory: "reports/subscriberHistory",
		getTransferAmountLedgerReport: "reports/transferAmountLedger",
		getRenewIntentReport: "reports/getRenewIntentReport",
		userSummary: "reports/userSummary",
	},
	resetPassword: {
		getCount: "resetPassword/getCount",
		list: "resetPassword/list",
		regenerateToken: "resetPassword/regenerateToken",
		resetPassword: "resetPassword/resetPassword",
	},
	retailer: {
		add: "retailer/add",
		edit: "retailer/edit",
		editUserStatus: "retailer/editUserStatus",
		get: "retailer/get/",
		getOperatorCount: "retailer/getCount",
		getPlanList: "retailer/getPlanList",
		getSelectList: "retailer/getSelectList",
		list: "retailer/list",
		teamAdd: "retailer/teamAdd",
		teamEdit: "retailer/teamEdit",
		teamList: "retailer/teamList",
	},
	role: {
		add: "role/add",
		edit: "role/edit",
		get: "role/get/",
		getMenu: "role/menu",
		getRoleCount: "role/getCount",
		getRolesForTeams: "role/getRolesForTeam",
		list: "role/list",
	},
	subscribers: {
		add: "subscribers/add",
		assignNewPlan: "subscribers/assignNewPlan",
		checkOttActivationStatus: "subscribers/checkOttActivationStatus",
		editSubscriber: "subscribers/edit",
		forcePlanCancel: "subscribers/forcePlanCancel",
		get: "subscribers/get/",
		getCount: "subscribers/getCount",
		getHistoryLog: "subscribers/getHistoryLog/",
		getNew: "subscribers/getNew/",
		getNewHistory: "subscribers/getNewHistory/",
		getNewPlan: "subscribers/getNewPlan",
		getRenewIntentRequest: "subscribers/getRenewIntentRequest",
		jioStarUpgradeRequest: "subscribers/jioStarUpgradeRequest",
		list: "subscribers/list",
		primeVideoUpgradeRequest: "subscribers/primeVideoUpgradeRequest",
		processRenewIntentBulk: "subscribers/processRenewIntentBulk",
		updateAutoRenewPlan: "subscribers/updateAutoRenewPlan",
		updateAutoRenewStatus: "subscribers/updateAutoRenewStatus",
		upgradePlan: "subscribers/upgradePlan",
	},
	superIsp: {
		addStackHolder: "superIsp/addStackHolder",
		addSubStackHolder: "superIsp/addSubStackHolder",
		creditDebitBalance: "superIsp/creditDebitBalance",
		edit: "superIsp/edit",
		get: "superIsp/get/",
		getCount: "superIsp/getCount",
		getIspList: "superIsp/getIspList",
		getSuperIspList: "superIsp/getSuperIspList",
		list: "superIsp/getList",
		syncPlan: "superIsp/syncPlan",
		teamList: "superIsp/teamList",
		getSuperIspTableList: "superIsp/getSuperIspTableList",
		getSuperIspPlanList: "superIsp/getSuperIspPlanList",
		getIspListForOper: "superIsp/getIspListForOper",
		getOperatorList: "superIsp/getOperatorList",
	},
	superDistributor: {
		addRetailer: "superDistributors/addRetailer",
		addStackHolder: "superDistributors/addStackHolder",
		createCommission: "superDistributors/createCommission",
		creditDebitBalance: "superDistributors/creditDebitBalance",
		edit: "superDistributors/edit",
		get: "superDistributors/get/",
		getCount: "superDistributors/getCount",
		getCouponDistributor: "superDistributors/couponDistributor",
		getDistListForSuperDist: "superDistributors/getDistListForSuperDist",
		getDistributorPlans: "superDistributors/getDistributorPlans",
		getDistForSuperDist: "superDistributors/getDistForSuperDist",
		getRetailersForSuperDist: "superDistributors/getRetailersForSuperDist",
		getIspPlanList: "superDistributors/getIspPlanList",
		getIspPlansCount: "superDistributors/getIspPlanCount",
		list: "superDistributors/getList",
		priceUpdate: "superDistributors/priceUpdate",
		syncPlan: "superDistributors/syncPlan",
		teamList: "superDistributors/teamList",
	},
	team: {
		add: "team/add",
		edit: "team/edit",
		editUserStatus: "team/editUserStatus",
		get: "team/get/",
		getCount: "team/getCount",
		getList: "team/list",
	},
	terms: {
		add: "terms/add",
		consentAccept: "terms/consentAccept",
		edit: "terms/edit",
		get: "terms/get/",
		getConsentData: "terms/getConsentData",
		getConsentFile: "terms/getConsentFile",
		getCount: "terms/getCount",
		list: "terms/list",
		publish: "terms/publish",
		revoke: "terms/revoke",
	},
};

export default apiList;
