export default [
  {
    category: "Agriculture And Allied",
    subcategories: [
      "Farm Machinery",
      "Fertilizers",
      "Hybrid Seeds",
      "Irrigation Systems",
      "Nurseries",
      "Saplings",
      "Tissue Culture Plants",
      "Farm Machinery and Equipment",
      "Vegetables",
      "Floriculture",
      "Dairy Farming",
      "Poultry Farming",
      "Livestock Farming",
      "Seeds, Fertilizers and Pesticides",
    ],
  },
  {
    category: "Banking, Finance, Insurance and Securities (BFIS)",
    subcategories: [
      "Banking Services",
      "Financial Services",
      "Insurance Services",
      "Capital Markets and Securities",
      "Digital Payments and FinTech",
      "Banking and Financial IT Systems",
      "Audit, Compliance and Consultancy",
    ],
  },
  {
    category: "Consultancy",
    subcategories: [
      "Business and Management Consulting",
      "Financial Consulting",
      "Human Resource Services",
      "Legal Consulting",
      "Engineering and Technical Consulting",
      "Marketing and Business Consulting",
      "Quality and Certification Consulting",
      "Architecture and Urban Development",
      "Travel and Tourism Consulting",
    ],
  },
  {
    category: "Defence And Aerospace",
    subcategories: [
      "Aircraft and Aerospace Services",
      "Defence Equipment Maintenance and Manufacturing",
      "Engineering and Technical Services",
      "Infrastructure and Facility Support",
      "Airport Ground Handling Services",
    ],
  },
  {
    category: "Education and Training",
    subcategories: [
      "Skill Development",
      "Training Programs",
      "Educational Supplies",
    ],
  },
  {
    category: "Energy, Power and Electrical",
    subcategories: [
      "Industrial Automation and Control",
      "Renewable Energy",
      "Non-Renewable Energy",
      "Power Supply and Electrification",
      "Power Transmission",
      "Protection Systems",
      "Substations and Switchyards",
      "Distribution Networks",
      "Transformers",
      "Poles and Conductors",
      "Cables",
      "Battery Energy Storage Systems",
      "Switchgear",
      "Distribution Boards",
      "Control Panels",
      "Generators",
      "Power Control Systems",
      "Software Development",
      "Electrical Equipment",
      "EV Infrastructure",
      "Lighting Systems",
    ],
  },
  {
    category: "Environment And Pollution",
    subcategories: [
      "Air Pollution Control Services",
      "Water Pollution Control Services",
      "Soil and Land Pollution Control",
      "Waste Management and Recycling Services",
    ],
  },
  {
    category: "Food and Beverages",
    subcategories: [
      "Catering Services",
      "Food Supply",
      "Mid Day Meal Services",
      "Food Grains and Cereals",
      "Pulses and Legumes",
      "Processed and Packaged Foods",
      "Dairy Products",
      "Meat, Poultry and Seafood",
      "Bakery and Confectionery",
      "Non-Alcoholic Beverages",
      "Alcoholic Beverages",
    ],
  },
  {
    category: "Healthcare and Medicine",
    subcategories: [
      "Healthcare Equipment",
      "Pharmaceutical Drug Categories",
      "Drug Forms and Pharma Operations",
      "Primary Health Services",
      "Ambulance and Emergency Services",
      "Herbal and Ayurvedic Medicines",
      "Surgical Instruments",
      "Patient Monitoring Systems",
      "Life Support Equipment",
      "Laboratory and Testing Services",
    ],
  },
  {
    category: "Industry",
    subcategories: [
      "Automobiles and Auto Parts",
      "Chemicals",
      "Construction Materials",
      "Furniture Supply",
      "Machinery and Equipment",
      "Paper and Packaging",
      "Plastic and Rubber",
      "Building Finishing Materials",
      "Textiles and Apparel",
      "Protective and Safety Clothing",
      "Footwear",
      "Synthetic Fibers",
      "Electronics Manufacturing",
      "Metals and Mining",
    ],
  },
  {
    category: "Information Technology",
    subcategories: [
      "Technology Hardware",
      "Smart Cards and Access Control Systems",
      "Alarm Systems",
      "GIS and GPS",
      "Web Application Development",
      "Mobile App Development",
      "Enterprise Software",
      "IT Services",
      "Cloud and Data Centers",
      "Cybersecurity",
      "Data and Analytics",
      "Emerging Technologies",
    ],
  },
  {
    category: "Infrastructure And Construction",
    subcategories: [
      "Housing and Building Development",
      "General Construction",
      "Industrial and Specialized Construction",
      "Repair, Maintenance and Renovation",
      "Earthworks and Foundation",
      "Roads and Highways",
      "Bridges and Tunnels",
      "Airports Infrastructure",
      "Commercial and Institutional Buildings",
      "Irrigation Infrastructure",
      "Civil Works",
      "Urban Development",
      "Smart Cities",
      "Industrial Parks",
    ],
  },
  {
    category: "Laboratory Equipment and Services",
    subcategories: [
      "Chemical Laboratory Supplies",
      "Lab Furniture and Infrastructure",
      "Laboratory Automation and Software",
      "Medical and Diagnostic Lab Equipment",
      "Testing and Consultancy Services",
      "Analytical Instruments",
      "Centrifuges",
      "Incubators",
      "Autoclaves",
      "Microscopes",
      "Glassware and Plasticware",
      "Reagents and Chemicals",
      "Radiology and Imaging Equipment",
      "Laboratory Software and IT Systems",
      "IoT-based Lab Monitoring",
    ],
  },
  {
    category: "Metals And Mining",
    subcategories: ["Aluminum", "Coal", "Minerals", "Mining Services", "Steel"],
  },
  {
    category: "Miscellaneous",
    subcategories: ["Others"],
  },
  {
    category: "Oil And Gas",
    subcategories: [
      "Exploration and Drilling",
      "Refining and Processing",
      "Transportation and Storage",
      "Distribution and Supply",
      "Infrastructure and Projects",
      "Testing and Inspection",
      "Digital and Automation",
      "Products and Equipment",
      "General Services",
    ],
  },
  {
    category: "Ports and Shipping Services",
    subcategories: [
      "Port Operations and Cargo Handling",
      "Marine and Vessel Services",
      "Shipbuilding and Port Infrastructure",
      "Logistics and Freight",
      "Environmental and Safety Services",
    ],
  },
  {
    category: "Printing and Publishing",
    subcategories: [
      "Commercial Printing Services",
      "Publishing Services",
      "Packaging and Label Printing",
      "Advertising and Display Printing",
      "Secure and Government Printing",
      "Pre Press and Finishing Services",
    ],
  },
  {
    category: "Railways",
    subcategories: [
      "Track Infrastructure",
      "Station Infrastructure",
      "Signalling and Electrical",
      "Rolling Stock and Maintenance",
      "Advanced Track Works",
    ],
  },
  {
    category: "Retail And Real Estate",
    subcategories: [
      "Retail Operations and Management",
      "Real Estate Development and Services",
      "Warehousing and Fulfillment",
      "Sale and Auction Services",
      "Solid Waste Management",
    ],
  },
  {
    category: "Security and Fire Safety",
    subcategories: [
      "Electronic Security Systems",
      "Security Services",
      "Fire Safety Systems and Equipment",
      "Emergency and Disaster Management",
      "Safety Equipment and PPE",
      "Industrial Safety Systems",
      "Road and Traffic Safety Equipment",
    ],
  },
  {
    category: "Services",
    subcategories: [
      "Entertainment and Media",
      "Postal and Courier Services",
      "Manpower Services",
      "Security Services",
      "Warehousing",
      "Freight Services",
      "Housekeeping",
      "Facility Management",
    ],
  },
  {
    category: "Sports and Leisure",
    subcategories: [
      "Coaching and Training Services",
      "Event Management",
      "Fitness and Gym Equipment",
      "Sports Equipment and Gear",
      "Outdoor and Adventure Sports Gear",
      "Indoor Games Equipment",
      "Sports Apparel and Footwear",
      "Yoga and Meditation",
    ],
  },
  {
    category: "Telecommunications",
    subcategories: [
      "Communication Systems",
      "Fiber Optics",
      "Telecommunications Networking",
      "Network Infrastructure",
      "Optical Fiber and OFC",
      "Networking",
      "Base Transceiver Stations (BTS)",
      "Antennas and RF Equipment",
      "Small Cells and DAS",
      "Telephony Systems",
      "Broadband and ISP Services",
      "VoIP Services",
      "Broadcasting",
      "Network Security",
      "Telecom Cybersecurity",
      "Data Encryption Systems",
      "Network Monitoring Tools",
    ],
  },
  {
    category: "Textiles And Apparel",
    subcategories: ["Fabrics", "Footwear", "Garments", "Uniforms"],
  },
  {
    category: "Transportation",
    subcategories: ["Aviation", "Marine Transport", "Railways", "Roadways"],
  },
  {
    category: "Water and Sanitation",
    subcategories: [
      "Water Supply Systems",
      "Water Treatment",
      "Sewerage and Wastewater",
      "Sanitation Infrastructure",
      "Water Recycling and Conservation",
      "Stormwater and Flood Management",
      "Plumbing and Materials",
    ],
  },
];
