export default [
	[
		{
			menu_id: 1,
			section_id: 1,
			name: "Dashboard",
			link: "/",
			image: "/images/sidebar/dashboard.svg",
			on_sidebar: 1,
			menus: [],
		},
		{
			menu_id: 18,
			section_id: 1,
			name: "Teams",
			link: "/team",
			image: "",
			on_sidebar: 0,
			menus: [],
		},
	],
	[
		{
			menu_id: 13,
			section_id: 5,
			name: "ISP",
			link: "/isp",
			image: "/images/sidebar/plans.svg",
			on_sidebar: 1,
			menus: [
				{
					menu_id: 14,
					section_id: 0,
					name: "Stakeholder",
					link: "/isp",
					image: "",
					on_sidebar: 1,
					menus: [],
				},
				{
					menu_id: 23,
					section_id: 0,
					name: "Super ISP",
					link: "/superIsp",
					image: "",
					on_sidebar: 1,
					menus: [],
				},
				{
					menu_id: 15,
					section_id: 0,
					name: "Plans",
					link: "/ispPlans",
					image: "",
					on_sidebar: 1,
					menus: [],
				},
				{
					menu_id: 16,
					section_id: 0,
					name: "Wallet",
					link: "/ispWallet",
					image: "",
					on_sidebar: 1,
					menus: [],
				},
			],
		},
		{
			menu_id: 12,
			section_id: 5,
			name: "Operators",
			link: "/operators",
			image: "/images/sidebar/operators.svg",
			on_sidebar: 1,
			menus: [],
		},
		{
			menu_id: 11,
			section_id: 5,
			name: "Operator Wallet ",
			link: "/operatorWallet",
			image: "/images/sidebar/wallet.svg",
			on_sidebar: 1,
			menus: [],
		},
		{
			menu_id: 63,
			section_id: 5,
			name: "Regions",
			link: "/regions",
			image: "/images/sidebar/operators.svg",
			on_sidebar: 1,
			menus: [],
		},
		{
			menu_id: 19,
			section_id: 1,
			name: "Onboarding",
			link: "/onboarding-engineer",
			image: "/images/sidebar/dashboard.svg",
			on_sidebar: 1,
			menus: [],
		},
	],
];
